version: '3.7'

services:

  mongodb:
    image: mongo
    container_name: TGDataset
    restart: always
    networks:
      - app-tier
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: Telegram_test
    volumes: 
      - /var/lib/docker/volumes/vol/_data

  python_app:
    build: .
    depends_on:
      - mongodb
    networks:
      - app-tier
    ports:
      - "8000:8000"
    environment:
      MONGO_INITDB_DATABASE: Telegram_test
    volumes:
      - /app/public_db


networks:
  app-tier:
    driver: bridge